### ISSUE TITLE
Time unit problem

### ISSUE THREAD

**Issue by crow1814** [egk696/SimpleSMTScheduler#2]
Thank you very much for your helping, I have successfully tried Command-line Mode.
However, I have some problems about time unit.  What is the unit of parameters, for example, Period, Execution, Deadline and wcet,  nanosecond, or microsecond?

**Comment by egk696** [comment]
It doesn't matter as long as all the inputs correspond to the same unit, i.e. microseconds. Usually, I input everything in microseconds as it is convenient for the hardware platform I use. Keep in mind that using nanoseconds instead of microseconds decreases the performance of the SMT solver simply because of bigger numbers, for this, I am planning to add a "granularity feature".

**Comment by crow1814** [comment]
thank you very much!

**Comment by egk696** [comment]
No problem, I will then close this issue!
